os: linux
language: node_js
node_js: node
matrix:
  allow_failures:
    - language: python
    - install: pyenv global 3.4.7
  include:
    - name: "Language: node_js, python3 --version"
      language: node_js
      install: python3 --version || python3 -m pip --version || true

    - name: "Language: python, Python 2.6"  # Unsupported release
      dist: trusty
      language: python
      python: 2.6

    - name: "Language: python, Python 3.2"  # Unsupported release
      dist: trusty
      language: python
      python: 3.2

    - name: "Language: python, Python 3.3"  # Unsupported release
      dist: trusty
      language: python
      python: 3.3

    - name: "Language: python, Python 3.4"  # Unsupported release
      dist: trusty
      language: python
      python: 3.4

    - name: "Language: cpp, Python 3.4.7"  # Unsupported release
      language: cpp
      before_install: pyenv install 3.4.7  # This takes time...
      install: pyenv global 3.4.7

    # Supported releases...
    - name: "Language: cpp, Python 2.7.15"
      language: cpp
      before_install: pyenv install --list
      install: pyenv global 2.7.15

    - name: "Language: cpp, Python 3.5.4"
      language: cpp
      before_install: pyenv install 3.5.4  # This takes time...
      install: pyenv global 3.5.4

    - name: "Language: cpp, Python 3.6.7"
      language: cpp
      install: pyenv global 3.6.7

    - name: "Language: cpp, Python 3.7.1"
      language: cpp
      install: pyenv global 3.7.1

    - name: "Language: node_js, Python 2.7.15"
      before_install: pyenv install --list
      install: pyenv global 2.7.15

    - name: "Language: node_js, Python 3.5.4"
      before_install: pyenv install 3.5.4  # This takes time...
      install: pyenv global 3.5.4

    - name: "Language: node_js, Python 3.6.7"
      install: pyenv global 3.6.7

    - name: "Language: node_js, Python 3.7.1"
      install: pyenv global 3.7.1

before_script:
  - python --version
  - chmod +x ./configure
script: ./configure
