os: linux
language: node_js
node_js: node
matrix:
  include:
    - name: "Language: cpp, Python 2.7.15"
      language: cpp
      before_install: pyenv install --list
      install: pyenv global 2.7.15

    - name: "Language: cpp, Python 3.4.8"
      language: cpp
      install: pyenv global 3.4.8

    - name: "Language: cpp, Python 3.4.9"
      language: cpp
      install: pyenv global 3.4.9

    - name: "Language: cpp, Python 3.4.10"
      language: cpp
      install: pyenv global 3.4.10

    - name: "Language: cpp, Python 3.5.4"
      language: cpp
      install: pyenv global 3.5.4

    - name: "Language: cpp, Python 3.5.5"
      language: cpp
      install: pyenv global 3.5.5

    - name: "Language: cpp, Python 3.5.6"
      language: cpp
      install: pyenv global 3.5.6

    - name: "Language: cpp, Python 3.5.7"
      language: cpp
      install: pyenv global 3.5.7

    - name: "Language: cpp, Python 3.6.7"
      language: cpp
      install: pyenv global 3.6.7

    - name: "Language: cpp, Python 3.7.1"
      language: cpp
      install: pyenv global 3.7.1

    - name: "Language: node_js, Python 2.7.15"
      before_install: pyenv install --list
      install: pyenv global 2.7.15

    - name: "Language: node_js, Python 3.6.7"
      install: pyenv global 3.6.7

    - name: "Language: node_js, Python 3.7.1"
      install: pyenv global 3.7.1

before_script:
  - python --version
  - chmod +x ./configure
script: ./configure
